version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bitemebee-network

  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=bitemebee
      - POSTGRES_USER=bitemebee
      - POSTGRES_PASSWORD=bitemebee
      - POSTGRES_SCHEMA=public
    ports:
      - "5433:5432"
    volumes:
      - ./docker-data/postgres/init:/docker-entrypoint-initdb.d/
    networks:
      - bitemebee-network

  app-main:
    container_name: app-main
    build:
      context: ./app-main
    restart: always
    depends_on:
      - postgres
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=bitemebee
      - DB_USER=bitemebee
      - DB_PASS=bitemebee
    networks:
      - bitemebee-network

  app-generator:
    container_name: app-generator
    build:
      context: ./app-generator
    restart: always
    depends_on:
      - app-main
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=generator
      - DB_USER=bitemebee
      - DB_PASS=bitemebee
    networks:
      - bitemebee-network

networks:
  bitemebee-network:
    driver: bridge