version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bitemebee-network

  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=bitemebee
      - POSTGRES_USER=bitemebee
      - POSTGRES_PASSWORD=bitemebee
      - POSTGRES_SCHEMA=public
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres/init:/docker-entrypoint-initdb.d/
    networks:
      - bitemebee-network

  app-main:
    container_name: app-main
    build:
      context: ./app-main
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=bitemebee
      - DB_SCHEMA=public
      - DB_USER=bitemebee
      - DB_PASS=bitemebee
      - RABBIT_HOST=rabbitmq
      - SELF_HOST=app-main
      - SELF_PORT=8080
      - GENERATOR_HOST=app-generator
      - GENERATOR_PORT=8081
    networks:
      - bitemebee-network

  app-generator:
    container_name: app-generator
    build:
      context: ./app-generator
    restart: always
    depends_on:
      - app-main
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=bitemebee
      - DB_SCHEMA=public
      - DB_USER=bitemebee
      - DB_PASS=bitemebee
      - RABBIT_HOST=rabbitmq
      - SELF_HOST=app-generator
      - SELF_PORT=8081
      - MAIN_HOST=app-main
      - MAIN_PORT=8080
    networks:
      - bitemebee-network

networks:
  bitemebee-network:
    driver: bridge