CREATE TABLE IF NOT EXISTS family_snapshots (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	activity float8 NOT NULL,
	created_at timestamp NOT NULL,
	drone_population_increase int8 NOT NULL,
	mood float8 NOT NULL,
	population_increase int8 NOT NULL,
	queen_population_increase int8 NOT NULL,
	worker_population_increase int8 NOT NULL,
	bee_family_id int8 NOT NULL,
	CONSTRAINT pk_family_snapshots_id PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS family_snapshots
    OWNER TO bitemebee;

ALTER TABLE IF EXISTS family_snapshots
    ADD CONSTRAINT fk_family_snapshot_on_bee_family FOREIGN KEY (bee_family_id) REFERENCES bee_families(id);