CREATE TABLE IF NOT EXISTS schedules (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	interval_in_minutes int8 NOT NULL,
	activity_id int8 NOT NULL,
	bee_type_id int8 NOT NULL,
	CONSTRAINT pk_schedules_id PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS schedules
    OWNER TO bitemebee;

ALTER TABLE IF EXISTS schedules
    ADD CONSTRAINT fk_schedule_on_activity FOREIGN KEY (activity_id) REFERENCES activities(id);

ALTER TABLE IF EXISTS schedules
    ADD CONSTRAINT fk_schedule_on_bee_type FOREIGN KEY (bee_type_id) REFERENCES bee_types(id);