CREATE TABLE IF NOT EXISTS generator_hives (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	current_honey_amount float8 NOT NULL,
	delta float8 NOT NULL,
	honey_capacity float8 NOT NULL,
	is_overheated bool NOT NULL,
	is_chilled bool NOT NULL,
	bee_family_id int8 NULL,
	CONSTRAINT pk_generator_hives_id PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS generator_hives
    OWNER TO bitemebee;

ALTER TABLE generator_hives
    ADD CONSTRAINT fk_generator_hive_on_generator_family FOREIGN KEY (bee_family_id) REFERENCES generator_families(id);