CREATE TABLE IF NOT EXISTS activities (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	is_planned bool NULL,
	title varchar(255) NOT NULL,
	CONSTRAINT pk_activities_id PRIMARY KEY (id),
	CONSTRAINT unique_activities_title UNIQUE (title)
);

ALTER TABLE IF EXISTS activities
    OWNER to bitemebee;

INSERT INTO activities (is_planned, title, id) VALUES
    (false, 'Собрать мёд', 1),
    (false, 'Выселить лишнюю матку', 2),
    (false, 'Проветрить улей', 3),
    (false, 'Вылечить пчелиную семью', 4),
    (true, 'Убрать мусор внутри улья', 5);