CREATE TABLE IF NOT EXISTS activities (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	is_planned bool NULL,
	title varchar(255) NOT NULL,
	CONSTRAINT pk_activities_id PRIMARY KEY (id),
	CONSTRAINT unique_activities_title UNIQUE (title)
);

ALTER TABLE IF EXISTS activities
    OWNER to bitemebee;

INSERT INTO activities (is_planned, title) VALUES
    (false, 'Собрать мёд'),
    (false, 'Выселить лишнюю матку'),
    (false, 'Проветрить улей'),
    (false, 'Вылечить пчелиную семью'),
    (false, 'Утеплить улей'),
    (true, 'Убрать мусор внутри улья');