CREATE TABLE IF NOT EXISTS users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"password" varchar(255) NOT NULL,
	username varchar(255) NOT NULL,
	CONSTRAINT pk_users_id PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS users
    OWNER to bitemebee;

INSERT INTO public.users (id, "password", username) VALUES
    (1, '$2a$10$RX5M1cZanK0BiRhBef5qrub2cxkrt02MTqNFBlDSmgeUHrXUtZzNC', 'admin');