CREATE TABLE IF NOT EXISTS hives (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	frame_count int4 NOT NULL,
	honey_amount float8 NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT pk_hives_id PRIMARY KEY (id),
	CONSTRAINT unique_hives_name UNIQUE (name)
);

ALTER TABLE IF EXISTS hives
    OWNER TO bitemebee;

--INSERT INTO hives (id, frame_count, honey_amount, "name") VALUES
--    (1, 8, 8.0, 'Большой жуж');
