CREATE TABLE IF NOT EXISTS bee_families (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	is_deleted bool NOT NULL,
	created_at timestamp NOT NULL,
	drone_population int8 NOT NULL,
	is_alive bool NOT NULL,
	note varchar(1000) NOT NULL,
	population int8 NOT NULL,
	queen_population int8 NOT NULL,
	worker_population int8 NOT NULL,
	bee_type_id int8 NOT NULL,
	hive_id int8 NULL,
	CONSTRAINT pk_bee_families_id PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS bee_families
    OWNER TO bitemebee;

ALTER TABLE IF EXISTS bee_families
    ADD CONSTRAINT fk_bee_family_on_hive FOREIGN KEY (hive_id) REFERENCES hives(id);

ALTER TABLE IF EXISTS bee_families
    ADD CONSTRAINT fk_bee_family_on_bee_type FOREIGN KEY (bee_type_id) REFERENCES bee_types(id);