CREATE TABLE IF NOT EXISTS hive_snapshots (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	co2 float8 NOT NULL,
	created_at timestamp NOT NULL,
	honey_increase float8 NOT NULL,
	humidity float8 NOT NULL,
	temperature float8 NOT NULL,
	hive_id int8 NOT NULL,
	CONSTRAINT pk_hive_snapshots_id PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS hive_snapshots
    OWNER TO bitemebee;

ALTER TABLE IF EXISTS hive_snapshots
    ADD CONSTRAINT fk_hive_snapshot_on_hive FOREIGN KEY (hive_id) REFERENCES hives(id);