spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bitemebee}
    username: ${DB_USER:bitemebee}
    password: ${DB_PASS:bitemebee}
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    schemas: public
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bitemebee}
    user: ${DB_USER:bitemebee}
    password: ${DB_PASS:bitemebee}

server:
  port: ${SELF_PORT:8081}

open-weather-client:
  url: https://api.openweathermap.org
  app-id: f3be4625645bd229b3c449602e5c8226

rabbit:
  titles:
    hive-queue: hive-snapshot
    family-queue: family-snapshot
    exchange: snapshot-exchange
  host-name: ${RABBIT_HOST:localhost}

generator:
  delay: 5000