spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bitemebee}
    username: ${DB_USER:bitemebee}
    password: ${DB_PASS:bitemebee}
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    schemas: public
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bitemebee}
    user: ${DB_USER:bitemebee}
    password: ${DB_PASS:bitemebee}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672

server:
  port: ${SELF_PORT:8080}

rabbit:
  titles:
    hive-queue: hive-snapshot
    family-queue: family-snapshot

feign-client:
  families-url: http://${GENERATOR_HOST:localhost}:${GENERATOR_PORT:8081}/api/generator_families
  hives-url: http://${GENERATOR_HOST:localhost}:${GENERATOR_PORT:8081}/api/generator_hives

jwt:
  jwtSecret: bitemebeeSecret
  jwtExpiration: 10000

verifier:
  delayMs: 60000