spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:bitemebee}
    username: ${DB_USER:bitemebee}
    password: ${DB_PASS:bitemebee}
  jpa:
    hibernate.ddl-auto: create
    open-in-view: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    schemas: public
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:bitemebee}
    user: ${DB_USER:bitemebee}
    password: ${DB_PASS:bitemebee}

rabbit:
  titles:
    hive-queue: hive-snapshot
    family-queue: family-snapshot